api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        jsonmerge: # Add this new format
            mime_types: [ 'application/merge-patch+json' ]  # Required for PATCH
        patch_formats:
            json: [ 'application/merge-patch+json' ]  # Enable for all PATCH operations